Trent/aero debug
machindustries/jsbsim pull request #2
Opened 2024-07-09 16:06 UTC by TrentConley

2024-07-17 19:03 UTC, mhand1998 commented on src/math/FGMatrix.cpp
> +double FGMatrix::GetValue() const {
might  be useful to include prototypes of the function in the .h file for type checking

2024-07-17 19:06 UTC, mhand1998 commented on src/math/FGMatrix.cpp
> +            temp << std::setprecision(8) << val;  // Set precision to 8 decimal places
Might be nice to have a constant in the header file to represent this value

2024-07-17 19:07 UTC, mhand1998 commented on src/math/Interpolation.cpp
> +const int MAX_CALLSTACK_DEPTH = 128;
might dropping a comment on how you determined this

2024-07-17 19:09 UTC, mhand1998 commented on src/math/Interpolation.cpp
> +double findLowerBound(const std::vector<double>& vec, double value) {
Can you create prototypes in the .h file for all the functions

2024-07-17 19:10 UTC, mhand1998 commented on src/math/FGMatrix.h
> +#include "VectorHash.h"  // Include the new header file
Where is this this Hash lib used?

2024-07-17 19:31 UTC, mhand1998 requested changes
Looks pretty good just a few minor nitpicks

2024-07-17 19:45 UTC, TrentConley commented on src/math/Interpolation.cpp
> +const int MAX_CALLSTACK_DEPTH = 128;
I used it for debugging the epison issue. Not needed anymore since I got rid of the stack trace function. It think epsilon can be decreased though. Will set it to std::numeric_limits<double>::epsilon() , which is 2.22045e-16 on my machine.

2024-07-17 19:53 UTC, TrentConley commented on src/math/FGMatrix.h
> +#include "VectorHash.h"  // Include the new header file
Line 104 of FGMatrix.cpp, `pointCloud.pointMap[coords] = value;`

2024-07-17 19:56 UTC, TrentConley commented on src/math/FGMatrix.cpp
> +            temp << std::setprecision(8) << val;  // Set precision to 8 decimal places
Agreed.

2024-07-17 20:05 UTC, TrentConley commented on src/math/Interpolation.cpp
> +double findLowerBound(const std::vector<double>& vec, double value) {
Yes

2024-07-18 00:02 UTC, mhand1998 approved these changes

2024-07-18 16:43 UTC, shua1090 approved these changes
I think some places could've used arrays rather than vectors (PointND, for example, though it would require some modifications of populatePointCloud() - though correct me if I'm wrong), but overall looks great to me! I like the tests.

2024-07-18 21:53 UTC, TrentConley commented
> I think some places could've used just arrays rather than vectors (PointND, for example, though it would require some modifications of populatePointCloud() - though correct me if I'm wrong; g++, at least, has variable length arrays), but overall looks great to me! I like the tests.

I don't think that it should be an array since we don't know the number of dimensions on compile time. It is determined in runtime when we pass in the matrix data. Thus, it needs to be stored in the heap rather than stack. I don't believe it is standard for C++ to have variable length arrays. I'm by no means a C++ expert though, I've just self-taught it so could be wrong here.

2024-07-22 23:29 UTC, merged

2024-07-22 23:39 UTC, shua1090 commented
Let's go!!!